
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    
        {!!HTML:: style('css/bootstrap.css')!!}
        {!!HTML:: style('css/default.css')!!}
        {!!HTML:: style('css/flexslider.css')!!}
        {!!HTML:: style('css/popou-box.css')!!}
        {!!HTML:: style('css/style.css')!!}
        {!!HTML:: style('css/styles.css')!!}
    
         {!!HTML:: script('js/jquery.min.js') !!}
        {!!HTML:: script('js/easyResponsiveTabs.js') !!}
        {!!HTML:: script('js/jquery.flexslider.js') !!}
        {!!HTML:: script('js/jquery.flexisel.js') !!}
        {!!HTML:: script('js/jquery.magnific-popup.js') !!}
       
        {!!HTML:: script('js/responsiveslides.min.js') !!}
        {!!HTML:: script('js/script.js') !!}

       


  @yield('content')






</html>