
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    
        {!!HTML:: style('css/bootstrap.css')!!}
        {!!HTML:: style('css/default.css')!!}
        {!!HTML:: style('css/flexslider.css')!!}
        {!!HTML:: style('css/popou-box.css')!!}
        {!!HTML:: style('css/style.css')!!}
        {!!HTML:: style('css/styles.css')!!}
        {!!HTML:: style('font-awesome/css/font-awesome.min.css')!!}
        {!!HTML:: style('font-awesome/css/font-awesome.css')!!}

        {!!HTML:: script('js/easyResponsiveTabs.js') !!}
        {!!HTML:: script('js/jquery.flexslider.js') !!}
        {!!HTML:: script('js/jquery.flexisel.js') !!}
        {!!HTML:: script('js/jquery.magnific-popup.js') !!}
        {!!HTML:: script('js/jquery.min.js') !!}
        {!!HTML:: script('js/responsiveslides.min.js') !!}
        {!!HTML:: script('js/script.js') !!}

        {!!HTML:: style('font-awesome/css/font-awesome.css')!!}
        {!!HTML:: style('font-awesome/css/font-awesome.min.css')!!}

        {!!HTML:: style('font-awesome/fonts/font-awesome.css')!!}
        {!!HTML:: style('font-awesome/fonts/font-awesome.min.css')!!}
        {!!HTML:: style('font-awesome/fonts/fontawesome-webfont.eot')!!}
        {!!HTML:: style('font-awesome/fonts/fontawesome-webfont.svg')!!}
        {!!HTML:: style('font-awesome/fonts/fontawesome-webfont.ttf')!!}
        {!!HTML:: style('font-awesome/fonts/fontawesome-webfont.woff')!!}
        {!!HTML:: style('font-awesome/fonts/fontawesome-webfont.woff2')!!}
        {!!HTML:: style('font-awesome/fonts/FontAwesome.otf')!!}

        {!!HTML:: style('font-awesome/less/animated.less')!!}
        {!!HTML:: style('font-awesome/less/bordered-pulled.less')!!}
        {!!HTML:: style('font-awesome/less/core.less')!!}
        {!!HTML:: style('font-awesome/less/fixed-width.less')!!}
        {!!HTML:: style('font-awesome/less/font-awesome')!!}
        {!!HTML:: style('font-awesome/less/icons.less')!!}
        {!!HTML:: style('font-awesome/less/larger.less')!!}
        {!!HTML:: style('font-awesome/less/list.less')!!}
        {!!HTML:: style('font-awesome/less/mixins.less')!!}
        {!!HTML:: style('font-awesome/less/path.less')!!}
        {!!HTML:: style('font-awesome/less/rotated-flipped.less')!!}
        {!!HTML:: style('font-awesome/less/stacked.less')!!}
        {!!HTML:: style('font-awesome/less/variable.less')!!}


  @yield('content')





</head>
    <body>
      
    </body>
</html>