
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    
        {!!HTML:: style('css/bootstrap.css')!!}
        {!!HTML:: style('css/default.css')!!}
       
        {!!HTML:: style('css/style.css')!!}
    
         {!!HTML:: script('js/jquery.min.js') !!}
      
       {!!HTML:: script('js/bootstrap.min.js') !!}
       
       {!!HTML:: script('src/html5-qrcode.js') !!}
       {!!HTML:: script('src/lib/html5-qrcode.min.js') !!}
       {!!HTML:: script('src/lib/jsqrcode-combined.min.js') !!}

       
  @yield('content')






</html>